### ISSUE TITLE
Decrements counter?

### ISSUE THREAD

**Issue by davidosomething** [rhysd/vim-operator-surround#29]
```
<?php
    $sponsor_info  = array(
        'na|me'    => $promoter_info[0]->post_title,
        'content' => $promoter_info[0]->post_content,
    );
```

cursor at the `|`, surround replace around `'` with `"` (switch to double quote) causes the `[0]` to decrement (like `C-x`) (using recommended mapping and keys: `sra'"`

**Comment by rhysd** [comment]
I'm closing this because it is not reproducible now. If someone sees this problem, please let me know by commenting here.
